# name: identify-app
# static_sites:
#   - name: frontend
#     source_dir: iDENTify-Web/frontend
#     build_command: npm install && npm run build
#     output_dir: dist
#     catchall_document: index.html


name: identify-app
services:
  - name: backend
    source_dir: iDENTify-Web/backend
    run_command: npm start
    envs:
      - key: PORT
        scope: RUN_TIME
        value: "8080"
static_sites:
  - name: frontend
    source_dir: iDENTify-Web/frontend
    build_command: npm install && npm run build
    output_dir: dist
    catchall_document: index.html
    envs:
      - key: VITE_API_BASE
        scope: BUILD_TIME
        value: https://identify-app-hth8t.ondigitalocean.app/identify-se-i-den-tify-web-backe